version: 0.2.x-{build}
image: Visual Studio 2022
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: ''
  package_version: 0.2.0-build{build}
environment:
  WEBHOOK_URL:
    secure: fWt3ENrCIAV+HeOIbySJsaNZhJtgcDERhakgi2asPmdPGIAGZ6RCntJQ1VAL7+re/V86azLFy0oL71cpbahN+xJ8M7qbHd5acRfIgOceiSji72s240Bg9ktGIMk3ARv9nRfh58cOT9VEZ1wOzfYOHmVOWY9spzreJSdcpDSLBMM=
before_build:
- cmd: nuget restore "%APPVEYOR_BUILD_FOLDER%\GRILO.sln"
build:
  verbosity: minimal
after_build:
- cmd: >-
    7z a devbuild.zip "%APPVEYOR_BUILD_FOLDER%\GRILO.Bootloader\bin\Debug\"

    7z a devbuild-boot.zip "%APPVEYOR_BUILD_FOLDER%\GRILO.Boot\bin\Debug\"
artifacts:
- path: devbuild.zip
  name: Development build of GRILO
- path: devbuild-boot.zip
  name: Development build of GRILO - Boot
- path: GRILO.Boot/bin/Debug/*.nupkg
- path: GRILO.Bootloader/bin/Debug/*.nupkg
deploy:
- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  api_key:
    secure: 2ocxItByklPOySTf0USeSC6NpQGHHkhYMzj08PlSKNZE/VxLSLzcQpdt4VMTQnJI
  symbol_server: https://www.nuget.org/api/v2/package
on_success:
- ps: >-
    Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1

    ./send.ps1 success $env:WEBHOOK_URL
on_failure:
- ps: >-
    Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1

    ./send.ps1 failure $env:WEBHOOK_URL
